### ISSUE TITLE
MPICH + OPENMP_NUM_THREADS=1 hangs

### ISSUE THREAD

**Issue by william-dawson** [william-dawson/NTPoly#143]

**Comment by william-dawson** [comment]
Idea: maybe setting OPENMP_NUM_THREADS=1 also sets the max threads to 1 in mpich. Maybe we should just raise an error in this case.

**Comment by william-dawson** [comment]
Thank you for your feedback @Dankomaister. I agree that it is an issue, and when using DFTB+ with NTPoly I personally resorted to modifying DFTB+'s source code (see: https://william-dawson.github.io/NTPoly/blog/update/2021/05/14/dftb.html). I will use your comments as motivation, take a look at it this week, and hopefully get it sorted out!

**Comment by bhourahine** [comment]
@william-dawson could you feed the threading issue back up-stream? From memory, the reason for disabling it was a claim that PEXSI(?) should only be run with one thread.

**Comment by william-dawson** [comment]
This should be fixed by #170 and the newly released version 2.7.0, so I am going to close this issue. The next steps are to update ELSI and then to update DFTB+.

**Comment by william-dawson** [comment]
DFTB+ has now addressed this issue: https://github.com/dftbplus/dftbplus/pull/854
On the ELSI side, I've submitted a pull request with the fix implemented in #170: https://gitlab.com/elsi_project/elsi_interface/-/merge_requests/281
