### ISSUE TITLE
MPI C datatype instead of Fortran datatype

### ISSUE THREAD

**Issue by Kokookster** [william-dawson/NTPoly#232]
One of our builds crashed because `MPI_LONG` is a MPI C datatype. I guess the correct corresponding MPI long integer in Fortran should be `MPI_INTEGER4 `.

I fixed this already in ELSI, but wanted to make sure this also goes into the main repo :)

**Comment by william-dawson** [comment]
Thanks. I think this was fixed in #208, but I wrote `MPI_INTEGER8` instead of `MPI_INTEGER4`! I should fix that, and create a new minor release.
