### ISSUE TITLE
MPI_IAllgather backup plan

### ISSUE THREAD

**Issue by william-dawson** [william-dawson/NTPoly#62]
Many machines still use versions of MPI without non blocking collectives. While the use of IAllgather (and Iallgatherv) is important for maximizing performance on new machines, having a backup routine that allows NTPoly to run on more machines would be helpful.

Probably the simplest solution is to just build a replacement routine, and then add a compile time switch between the two. The replacement routine would have to be based on isend/irecv. Using the blocking all gather isn't an option because any implementation that doesn't have non-blocking collectives probably doesn't have anything like `MPI_THREAD_SERIALIZED`, so we'd lose all the overlapping of communication and computation.

**Comment by wphuhn** [comment]
This is Will, I'm a post-doc that works on ELSI and FHI-aims.  We ran into this issue on our local development cluster, where the integration of NTPoly into ELSI forced us to upgrade the versioning for supported MPI libraries.

From our tests, the MPI libraries which NTPoly (in ELSI) can link against are:
- Intel MPI 2015 (according to Victor, I've only tried 2018)
- OpenMPI 1.7.5
- MPICH 3.0.4*
* We run MPICH 3.1.4. in our CI, as 3.0.4 fails several regression tests.

The MPI libraries that NTPoly (in ELSI) cannot linked against are:
- Intel MPI 2014
- OpenMPI 1.6.5

Not sure if this helps in any way, but I figured I'd let you know, just in case.

**Comment by william-dawson** [comment]
Victor also mentioned BlueGene Q, so we can add whatever IBM calls their MPI implementation to the list. I have a branch now with a send/recv based drop in replacement, and I'll do performance tests on it once the K compuer is done with its large job runs. I'll keep you guys posted!

**Comment by william-dawson** [comment]
Fixed by #63
